version: "3.8"

services:
  oracle:
    container_name: oracledb-23
    build: .
    restart: unless-stopped
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=renaissance
    volumes:
      - data:/opt/oracle/oradata
      - dbs:/opt/oracle/product/23c/dbhomeFree/dbs
  
volumes:
  data:
    name: oradata
  dbs:
    name: oracle-dbs