version: "3.8"

services:
  oracledb:
    container_name: oracledb-23
    build: .
    restart: unless-stopped
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=renaissance
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-dbs:/opt/oracle/product/23c/dbhomeFree/dbs
  
volumes:
  oracle-data:
    name: oradata
  oracle-dbs:
    name: oracle-dbs