version: "3.8"

services:
  oracledb:
    container_name: mde-oracledb
    image: container-registry.oracle.com/database/free:latest
    ports:
      - "1522:1521"
    environment:
      - ORACLE_PWD=renaissance
    volumes:
      - ./scripts:/opt/oracle/scripts/startup
      - oracle-data:/opt/oracle/oradata
      - oracle-dbs:/opt/oracle/product/23c/dbhomeFree/dbs
  
volumes:
  oracle-data:
    name: oradata
  oracle-dbs:
    name: oracle-dbs