version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: elasticsearch
    environment:
      - node.name=es_node_01
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=${PASSWORD}
    mem_limit: ${ES_MEM_LIMIT}
    ports:
      - ${ES_PORT}:9200
    networks:
      - es-net
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    depends_on:
      elasticsearch:
        condition: service_healthy
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: kibana
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${PASSWORD}
    ports:
      - ${KIBANA_PORT}:5601
    networks:
      - es-net
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

networks:
  es-net:
